### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#103]
Just updated to 1.3 here. Noticed a couple issues with the search functionality

**Short search terms**
Unexpected results with short search terms (3 characters or less)

**Repeated search results**
Topics are repeated in search results. If it's intentional to have the topic listed for each instance of a search term, could you include an excerpt of the post reply that contains the search term on the search results page? Additionally would it be possible that the topic links go to the specific messages that include the search terms rather than just the first page of the topic?

**Last post**
The last post header is missing on the search results page

<img width="809" alt="screen shot 2016-12-14 at 1 58 24 pm" src="https://cloud.githubusercontent.com/assets/5422422/21196383/6c05f9bc-c205-11e6-9d5b-c3b7d6bfb27b.png">

**Comment by jangevaare** [comment]
A couple other things I noticed. In topic view, the topic title is now empty, and the breadcrumbs are removed. Unsure if this was intentional or not, but it looks like it was cut off or something - a bit weird!

The larger avatars look good in 1.3.0! They aren't centred for me though (they weren't previously either)

in 1.2.9:
<img width="1003" alt="screen shot 2016-12-14 at 2 18 34 pm" src="https://cloud.githubusercontent.com/assets/5422422/21197162/6b59c3c4-c208-11e6-8d77-c9e382789131.png">



in 1.3.0:
<img width="921" alt="screen shot 2016-12-14 at 2 16 52 pm" src="https://cloud.githubusercontent.com/assets/5422422/21197167/7039c61e-c208-11e6-88b1-2732397c013a.png">

Cheers.

**Comment by Asgaros** [comment]
Hello @jangevaare 

First of all: Thanks for your feedback! Regarding the look of the searchbar and some parts of the lastpost-area: Please clear your browser cache or reload your forum-page with CTRL+F5 because the new stylesheets seem not to be loaded.

I will check the other points tomorrow because it is already late in germany. :-)

**Comment by jangevaare** [comment]
Okay, did that, and it did fix a bunch of the issues - I'll go back and edit my initial post. Thanks!

**Comment by Asgaros** [comment]
@jangevaare 

Regarding the problem with short search terms: The minimum word-length for a fulltext-search is defined in a MySQL system variable. So when you want to allow shorter terms, you have to change the settings of your MySQL-server. You can find more information about this here:
http://dev.mysql.com/doc/refman/5.5/en/fulltext-fine-tuning.html

The purpose of this is to ignore meaningless words like _"and"_, _"an"_, _"so"_, _"the"_, etc because they appear in almost every text multiple times which would lead to a huge number of useless search results.

**Comment by jangevaare** [comment]
Thank you, indeed my minimum word length for a full text search is set to 4! Is it possible to give an error page rather than confusing search results when a search term is less than the system minimum? Cheers!

**Comment by Asgaros** [comment]
@jangevaare 

What exactly do you mean with "confusing search results"? At the moment it says that there are no results for your search. Do you have an idea of a better way? Or do you get different results in your testing environment?

**Comment by jangevaare** [comment]
Example below with a 3 character search term. There are some search results but there shouldn't be. I do think it's a good idea to distinguish "No results found for" and "Search term too short" if possible

<img width="1005" alt="screen shot 2016-12-16 at 9 40 47 am" src="https://cloud.githubusercontent.com/assets/5422422/21266361/db88b238-c373-11e6-94b5-7f1ae4a2adad.png">

**Comment by Asgaros** [comment]
@jangevaare 

Normally there should be **no** results for words which are too short **or** when the search cant find anything. But the search is also matching the search key against parts of the word. So a search for _"air"_ also shows posts which contains words like _"**air**plane"_.

Are you sure that you dont have words like this in that topics? Because otherwise it would show _"No results found for: air"_.
