### ISSUE TITLE
Unread count update takes too long

### ISSUE THREAD

**Issue by uncovery** [Asgaros/asgaros-forum#130]
I have about 8k posts and users complain that the forum does not come up. When I disable the forum unread count update, the forum is there instantly.

I comment out this line here: https://github.com/Asgaros/asgaros-forum/blob/master/includes/views/forum-element.php#L13

**Comment by Asgaros** [comment]
Hello @uncovery 

Are you using the latest version (1.5.1) of the forum? I will take a look into it.

**Comment by uncovery** [comment]
yes, it's 151

**Comment by Asgaros** [comment]
Hello @uncovery 

I just created ten-thousands of posts and topics and everything is running fast for me.

Are you sure that the forum-unread.php file containts the actual content? Because I made some changes to it which fixed those kind of problems in a previous update.

Can you also post the full configuration of your forum (Forum -> Options)?

Does this performance problem occur only for guests/logged-in users/administrators or all?

**Comment by Asgaros** [comment]
What you also can try to do:

Open the file **asgaros-forum/includes/forum-unread.php**

Search for the _getStatusForum_-function

Comment out the following part:
```

    foreach ($lastpostList as $key => $lastpostListItem) {
                // This topic has not been opened yet, so it is actually the last post.
                if (!isset(self::$excludedItems[$lastpostListItem->parent_id])) {
                    $lastpostData = $lastpostListItem;
                    break;
                }

                // This topic has been opened, but there is already a newer post, so it is actually the last post.
                if (isset(self::$excludedItems[$lastpostListItem->parent_id]) && $lastpostListItem->id > self::$excludedItems[$lastpostListItem->parent_id]) {
                    $lastpostData = $lastpostListItem;
                    break;
                }
            }
```

Check if it is still slow.

This could help me to find the part of code which is responsible for that.

**Comment by uncovery** [comment]
Can you tell me what I need to do to reset the unread status for a user so that it's like he never has been on the forum?

**Comment by Asgaros** [comment]
You have to delete the following user-meta-data:
- asgarosforum_unread_cleared
- asgarosforum_unread_exclude

**Comment by uncovery** [comment]
Hi, sorry, I was very busy so I could not follow up on this. 
I tried your solution now with 1.5.3 and it does not help.

Commenting out the line 13 as described in the initial post works however.

**Comment by uncovery** [comment]
Regarding the forum options:

Replies to show: 20, Topics: 40
All checked boxes except; Allow Shortcodes, Forum visible to logged in only, allow signatures, allow guest postings. Guests can upload files, show uploads to logged in only.
Files per post and max file size is 5

Hope this helps.

**Comment by Asgaros** [comment]
Hello @uncovery 

I still really have difficulties to reproduce it on my testing-machine with thousands of topics/posts. Other queries are also not different compared to that, so I really wonder whats the cause of it ...

Is it possible somehow to get a database-dump of the forum-tables (wp_forum_posts/wp_forum_topics/wp_forum_forums) so I can have a closer look and test it with it? If yes, please send it to me at _developer(at)thomasbelser.net_.

**Comment by uncovery** [comment]
sent.

**Comment by Asgaros** [comment]
Thank you, I got it! I will check it out and try to increase the performance. :)

**Comment by Asgaros** [comment]
Hello again, @uncovery 

Please download this development-version and replace the files on your web-server with a FTP-client:
https://github.com/Asgaros/asgaros-forum/archive/642962397d7ee95bdeee503eeb9621edc68c4fb6.zip

The code should be stable. I only cleaned up a couple of queries and (more important) added an index to the parent_id-column in the posts-table. This should speed up a lot of queries.

Please give me feedback after testing so that I can release an updated-version soon.

**Comment by uncovery** [comment]
thanks, this worked!
