### ISSUE TITLE
Read/unread status of forum behaviour

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#150]
Your constant improvement of this software has been great. Cheers!

Something that has come up with us, is that there is a bit of confusion amongst users on our site about read/unread status of forums. The behaviour they expect is if there are no new replies in the forum since they last visited it, it will appear as read. The actual behaviour though, from my understanding, is that unless they have read every single topic in the forum, it will still appear as being unread, even if there is nothing new since their last visit. For large forums - as ours is becoming - this is pretty unlikely, and marking all as read on a regular basis is a little crude. The issue is heightened on mobile, as the last post column will be hidden. I have learned most of our users have just assumed read/unread status doesn't work on the forum-wide level. Are there any workarounds for this? Thanks!

**Comment by Asgaros** [comment]
Hello @jangevaare 

This is a good point - but hard to find a solution for because everyone has a different expectation on this behavior.

- **Scenario 1:** Some users expect that it only shows the _"unread"_-indicator when there are new posts since their last visit. I think the best solution for this is the current way of using the _"Mark as read"_-button. Because its the only possibility that this functionality takes care of the next two examples.
- **Scenario 2:** Its hard to define your _"last visit"_. Imagine you are reading a topic which consists of very long posts. Maybe you need ten minutes to read them because its a long guide or you get disturbed between. Technically you are not listed in the _"Who is online?"_-area anymore after ten minutes. When you now go back to read all other topics which were marked as _"unread"_, you will have a problem. Because they would now be marked as _"read"_ due to the fact that the plugin assumes its a new visit (because you were _"inactive"_ for more than ten minutes).
- The **third scenario** is the way on how I am using forums. I am often busy or in a hurry so I quickly want to check if there are some new topics or posts inside my forums. So I have time to check two or three of the new topics and want to come back later to check the remaining ones. With your suggestion it would be again impossible to track all unread topics later because the plugin would now only take those topics/posts into consideration which were created since my last visit. Especially for support-forums this would be very bad because it would be impossible to track all unchecked requests.

Thats the reason why I dont want to change anything on the current behavior because I think it would make things more confusing for a lot of users. The _"Mark all read"_-button is a good trade-off I think.
