### ISSUE TITLE
Email notifications: instant vs. daily or weekly digests

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#158]
Hello!
With the @mention notification emails especially, some users may receive high volumes of notification emails without any method of turning them off. It would be great to be able to offer them options of none/instant/daily digest/weekly digest options to the subscriptions and @mentions.
Cheers!
Justin

**Comment by ray004** [comment]
I, as an end user, would like to be able to turn off '@mention' notifications. as they are a duplicate email if I  have already subscribed to 'topic reply;' notifications
Also as I mentioned elsewhere an interface to mailchimp "use MailChimp to send WordPress blog posts" would also be good

**Comment by Asgaros** [comment]
Hello @ray004 

A new option to turn off mentioning-notifications per users is a good idea. I created an own GitHub issue for this and will try to implement it in the next update:
https://github.com/Asgaros/asgaros-forum/issues/173

**Comment by Asgaros** [comment]
The next update will come with a new option in the backend-profile which allows users to disable notifications when they get mentioned.

I dont plan to integrate a Daily/Weekly notification-summary yet because it would require the implementation of an own CronJob or the use of the WP-Cron API. One of the problems of the WP-Cron API is: It only gets triggered when a user visits your site. When you have a small community with less visitors there is always the risk that the summary arrives later than expected.

I think with the latest changes in the notifications-overview and the addition of the activity feed its more easy for user to get rid of annoying subscriptions while still staying up-to-date about recent posts.

**Comment by ray004** [comment]
i believe the RSS feed / mailchimp linkage would overcome the Cron issues.  
My understanding is that you would have to create a rss feed (of new topics and/or replies , new forums, etc) and then mailchimp reads that on a daily/weekly basis to send email of 'extracts' based on the rules I apply within mailchimp
I'm still testing this linkage but it seems to working well for me with other custom rss feeds

**Comment by Asgaros** [comment]
@ray004 

Yes, RSS-Feeds should be easy to implement and when you have a reader which only reads it once per day/week then its fine.

You can follow the following ticket to stay up2date about the rss-implementation:
https://github.com/Asgaros/asgaros-forum/issues/116
