### ISSUE TITLE
The SEO Framework title generation conflict

### ISSUE THREAD

**Issue by LeBaux** [Asgaros/asgaros-forum#206]
Hi, one of your users opened a ticket unveiling [title generation conflict with The SEO Framework and Asharos](https://wordpress.org/support/topic/disable-seo-framework-on-a-specific-page/). If your plugin registered post types #85, Normally, TSF could be easily partially disabled via backend, [like bbPress](https://i.imgur.com/76hulv9.png). I think this would be a proper way to address the issue in a WordPress friendly way. This could also potentially help with #10 #46 #55 and improve general compatibility with other plugins and possibly themes. Unless you see a better way. Thanks!

Also, as a side note, [this probably shouldn’t be possible](https://i.imgur.com/bMISmyl.gif).

**Comment by Asgaros** [comment]
Hello @LeBaux 

Custom Post Types are not an option for a forum-plugin because WordPress does not provide a "good API" in terms of performance which allows accessing data in a deep parent-child-structure using different post types (e.g. Select last post of topic A,B,C in sub-forum X in forum Y of category Z). This is the reason why Asgaros Forum uses its own database-tables and content-structure like other popular forum-plugins (wpForo for example).

Usually SEO-plugins - like Yoast SEO - provides options to disable its meta-generation for certain pages or at least filters/hooks which allows site-owners/developers to control certain steps of your login without directly modifying core-files of the plugin. I suggest you to add such a feature because a lot plugins already ensure that correct meta-tags are set inside the pages used by a certain plugin.

Just another example: Assume I would use custom post-types for forum-topics and forum-posts. If you visit a forum-topic your plugin would now assume to show meta-tags based on the forum-topic post-type. However, this would not be the optimal way in a forum because for a topic the meta-output like descriptions also depends on the content of the first forum-post inside of a forum-topic - which would be a completely different post-type. Thats why Asgaros Forum already takes care of SEO inside of forum-pages.

**Comment by LeBaux** [comment]
I understand your point and thank you for the explanation and time. For future reference, if anyone is looking to make The SEO Framework (TSF) compatible* with Asgaros forums, all you have to do is paste this snipet into your theme’s `function.php` (or better yet, in child theme):

```php
add_action( 'asgarosforum_prepare', function() {
   if ( function_exists( 'the_seo_framework' ) ) {
        remove_action( 'wp_head', [ the_seo_framework(), 'html_output' ], 1 );
   }
} );
```

*Compatible = Asgaros is taking care of SEO on it’s forum pages, TSF everywhere else.
