### ISSUE TITLE
Feature Request: mentions in quotes

### ISSUE THREAD

**Issue by r3dunlop** [Asgaros/asgaros-forum#208]
Would it be possible to block the regular mention functionality when the mention is located in a quote? With the current setup, if user_1 asks a question mentioning user_2, and user_2 responds by quoting the question, user_2 recieves an email saying that they were mentioned. I beleive that this should be easy to block, and a flag could be used that allows admin to select whether they want to leave this functionality in or not.

**Comment by Asgaros** [comment]
Hello @r3dunlop 

Thank you for your suggestion! I will try to include this Enhancement in the v1.14 release.

Note for myself:
https://stackoverflow.com/questions/11165895/php-strip-tags-remove-only-certain-tags-and-their-contents

**Comment by Asgaros** [comment]
I just uploaded a commit to the development-version which should fix this issue. A stable development-version which contains this fix can be donwloaded here:
https://github.com/Asgaros/asgaros-forum/archive/a98356cc53c25bd2431fe284a7adcd26c8c110cc.zip

Some testing-feedback would be great because implementing this fix was a little bit tricky!

**To ensure that this fix works, the PHP-extension _libxml_ must be activated on the server. This extension is activated in PHP by default, so this should work fine in most cases. However, if this extension is not available, the logic will not run. A solution without this extension is not possible because there is no save way to find nested blockquotes inside a string just by using regular-expressions.**

**Comment by r3dunlop** [comment]
I will take a look when I get a chance. Thanks!
