### ISSUE TITLE
User Profile 

### ISSUE THREAD

**Issue by libflashy** [Asgaros/asgaros-forum#98]
Hi, I have a website where users have their own personal profile and I noticed in your forum plugin  that it displays the users photo (from their profile) but it doesn't allow you to click the photo and it will bring you to their personalized profile. Will there ever be an update so that this will be possible?

**Comment by Asgaros** [comment]
Hello @libflashy 

I think that you are using some kind of WordPress PlugIn for that user-profile functionality. Thats the reason why I can't provide links for this by default because there are hundreds of PlugIns for this kind of stuff which are all working differently.

You can try to add the profile-link by yourself using one of the filters I provide with the plugin. The definition for the one you has to use is the following:
`do_action('asgarosforum_after_post_author', $post->author_id, $post->author_posts);`

**Comment by libflashy** [comment]
I am new to this whole hooks and filter stuff... Where would this be located?

**Comment by libflashy** [comment]
Where do I put this code. I'm new and not familiar with hooks or filters

**Comment by jangevaare** [comment]
I have the following in functions.php in a child theme to get a profile link

```
add_action('asgarosforum_after_post_author', 'my_function', 10, 1);

function my_function($author_id) {
	$user_info = get_userdata($author_id);
	echo '<p><a href="'.get_bloginfo('wpurl').'/profile/'.$user_info->user_login.'" title="profile">profile</a></p>';
}
```

**Comment by libflashy** [comment]
yea I do to now and its still not letting me click onto the users profile

**Comment by jangevaare** [comment]
@libflashy The profile locations may be different in your situation than in mine (hence why this isn't included in the forum software). You will have to modify the above code based on where profiles are located on your site.

**Comment by libflashy** [comment]
Ok thank you. Lol I'm truly not familiar with any of this language
